name: Tests

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install modules
        run: npm install

      - name: Add ci
        run: npm ci

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Get coverage
        continue-on-error: true
        run: npm run coverage

      - name: Use the Upload Artifact Github Action
        uses: actions/upload-artifact@v3
        with:
          name: report
          if-no-files-found: error
          path: ./coverage

      - name: Publication coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          if-no-files-found: error
          path: html-report/index.html

      - name: 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html-report
          clean: true
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Send report to telegram
        run: "curl -X POST https://api.telegram.org/bot${{secrets.BOT_TOKEN}}/sendMessage -H \"Content-Type: application/json\" -d '{\"chat_id\": \"${{secrets.CHAT_ID}}\", \"text\": \"Report link is: ${{env.GITHUB_ACTION_PATH}}/${{env.GITHUB_ACTION}}\"}'"


