name: Tests

on: [push]

jobs:
  test:
   environment:
     name: github-pages
     url: ${{ steps.deployment.outputs.page_url }}

   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
         node-version: 16
         cache: npm

     - name: Install modules
       run: npm install

     - name: Add ci
       run: npm ci

     - name: Get coverage
       continue-on-error: true
       run: npm run coverage

     - name: Use the Upload Artifact Github Action
       uses: actions/upload-artifact@v3
       with:
         name: report
         if-no-files-found: error
         path: test-report/index.html

     - name: Publication coverage report
       uses: actions/upload-artifact@v3
       with:
         name: coverage
         if-no-files-found: error
         path: coverage

     - name: Deploy
       uses: JamesIves/github-pages-deploy-action@v4
       with:
         folder: coverage/lcov-report
         clean: true
         token: ${{ secrets.TOKEN }}

